server:
  port: 22100
spring:
  application:
    name: xc-service-base-filesystem
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/xc_course?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
  data:
    mongodb:
      uri: mongodb://root:root@127.0.0.1:27017
      database: xc_fs
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      location:
      max-file-size: 2MB
      max-request-size: 30MB

xuecheng:
  fastdfs:
    connect_timeout_in_seconds: 5
    network_timeout_in_seconds: 30
    charset: UTF-8
    tracker_servers: 192.168.101.33:22122