# 数据源
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/mydb?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    suffix: .html
    prefix: classpath:templates/

# 整合mybatis
mybatis:
  type-aliases-package: com.yil3.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml

