
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mydb?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

# mybatis:
#   type-aliases-package: com.universe.entity
#   mapper-locations:
#   - classpath:com/universe/mapper/*.xml

mybatis-plus:
  type-aliases-package: com.universe.entity
  mapper-locations:
  - classpath:com/universe/mapper/*.xml
