server:
  port: 9527
spring:
  application:
    name: cloud-gateway-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/find/**
        - id: payment_routh
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/**






eureka:
  client:
    register-with-eureka: true     # true表示向注册中心注册自己 默认为true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
