server:
  port: 31001
spring:
  application:
    name: xc-service-manage-cms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/ihrm?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: xc_cms
  rabbitmq:
    virtual-host: /cms
    host: 192.168.101.33
    port: 5672
    username: guest
    password: guest
  freemarker:
    cache: false
    settings:
      template_update_delay: 0
logging:
  level:
    com.xuecheng.manage_cms.dao: debug
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka01.com:50101/eureka/